### ISSUE TITLE
Update to Quantum?

### ISSUE THREAD

**Issue by morkthedork** [Wykks/Untamed-Now-Playing-Next#173] opened 2017-11-14 20:36 UTC
This is still a legacy addon, are the devs able to update this to firefox build 57+? Or can we just do this on our own?

**Comment by Wykks** [comment] 2017-11-14 20:43
https://github.com/Wykks/Untamed-Now-Playing-Next#important-information :)

**Comment by Wykks** [comment] 2017-11-15 09:09
Closing as duplicate of https://github.com/Wykks/Untamed-Now-Playing-Next/issues/142

**Closed by Wykks** 2017-11-15 09:09 UTC
