### ISSUE TITLE
Pandora broke

### ISSUE THREAD

**Issue by FasterThanLlamas** [Wykks/Untamed-Now-Playing-Next#129] opened 2017-02-18 00:16 UTC
Pandora isn't updating output files.  I see their UI changed...

**Comment by Senpos** [comment] 2017-02-18 10:58
@FasterThanLlamas Can you provide screenshot of the new UI and way to enable it? Cuz it seems like [working for me](http://i.imgur.com/ZzXBoGW.png).

**Comment by FasterThanLlamas** [comment] 2017-02-18 15:29
I don't know how to enable it, but here's the image.  I was able to switch back to the old site and it's working there.

<img width="1172" alt="capture" src="https://cloud.githubusercontent.com/assets/19563780/23094337/cd18016c-f5ab-11e6-9033-3cf0ebd7083f.PNG">

**Comment by Scarfninja** [comment] 2017-02-20 00:01
I have the same pandora right now Fast, how did you get it to revert back to the original so I can get this fixed till there's a fix for the new layout?

**Comment by FasterThanLlamas** [comment] 2017-02-20 01:04
No problem. Thanks!

**Comment by Senpos** [comment] 2017-02-20 12:30
It seems that new web version design only avaliable for Pandora Plus (paid) users.

**Comment by Scarfninja** [comment] 2017-02-20 15:42
I'm not sure cause I know I'm not a paid user of Pandora I just have the
latest adobe flash installed. It wouldn't let me.l use pandora until I'd
updated and now it looks like Fasts

**Comment by Wykks** [comment] 2017-02-20 21:52
I have the old interface too... I'll try with different setup next time

**Comment by kyler2miler** [comment] 2017-04-04 00:20
@Wykks has there been any progress on this?  I already dislike the new Pandora UI, but to have it not work with UNP is beyond frustrating.

**Comment by FasterThanLlamas** [comment] 2017-04-04 02:00
In your settings you can roll back to the old UI.

**Comment by kyler2miler** [comment] 2017-04-04 02:06
@FasterThanLlamas well shiver me timbers, thanks

**Comment by danielsangeo** [comment] 2017-05-02 04:53
Pandora is now reporting "The classic version of Pandora.com will soon be shut down."  The "improved site" (their words) still is not working with UNP. I don't know when they'll be getting rid of the classic (working) version.

**Comment by MCplattipus94** [comment] 2017-05-08 20:19
Pandora no longer has the classic version. UNP needs to be updated to crawl the new UI

**Comment by danielsangeo** [comment] 2017-05-09 05:11
Confirmed that Pandora no longer has the classic version.  UNP is not working at all with Pandora now.

**Comment by Senpos** [comment] 2017-06-23 11:45
Fixed in #156. Seems to work fine now. If you have any problems - create new Issue. Closed.

**Comment by Senpos** [comment] 2017-06-23 11:45
Fixed in #156. Seems to work fine now. If you have any problems - create new Issue. Closed.

**Closed by Senpos** 2017-06-23 11:45 UTC
Labels: Website support issue
